"""add provider field to credential table

Revision ID: 1544be8eed51
Revises: 543f97951bd0
Create Date: 2025-04-28 18:13:26.252785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1544be8eed51'
down_revision = '543f97951bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('credential_organization_id_fkey', 'credential', type_='foreignkey')
    op.create_foreign_key(None, 'credential', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credential', type_='foreignkey')
    op.create_foreign_key('credential_organization_id_fkey', 'credential', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('credential', 'provider')
    # ### end Alembic commands ###
