from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '42f6f61b4443'
down_revision = '543f97951bd0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    
    # 1. Drop the old user_id column (UUID type)
    op.drop_column('apikey', 'user_id')

    # 2. Add the new user_id column (Integer type)
    op.add_column('apikey', sa.Column('user_id', sa.Integer(), nullable=False))
    
    # Drop and recreate the foreign key constraint on credential table
    op.drop_constraint('credential_organization_id_fkey', 'credential', type_='foreignkey')
    op.create_foreign_key(None, 'credential', 'organization', ['organization_id'], ['id'])

    # 3. For the document table, do the same:
    # Drop the old columns and add the new columns with Integer type
    op.drop_column('document', 'id')
    op.add_column('document', sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))

    op.drop_column('document', 'owner_id')
    op.add_column('document', sa.Column('owner_id', sa.Integer(), nullable=False))

    # 4. For the projectuser table, change user_id from UUID to Integer
    op.drop_column('projectuser', 'user_id')
    op.add_column('projectuser', sa.Column('user_id', sa.Integer(), nullable=False))

    # 5. For the user table, change id from UUID to Integer
    op.drop_column('user', 'id')
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    
    # Reverting changes by going back to UUID
    op.drop_column('apikey', 'user_id')
    op.add_column('apikey', sa.Column('user_id', sa.UUID(), nullable=False))
    
    op.drop_column('document', 'id')
    op.add_column('document', sa.Column('id', sa.UUID(), nullable=False, autoincrement=True))

    op.drop_column('document', 'owner_id')
    op.add_column('document', sa.Column('owner_id', sa.UUID(), nullable=False))

    op.drop_column('projectuser', 'user_id')
    op.add_column('projectuser', sa.Column('user_id', sa.UUID(), nullable=False))

    op.drop_column('user', 'id')
    op.add_column('user', sa.Column('id', sa.UUID(), nullable=False, autoincrement=True))

    # ### end Alembic commands ###
