"""add_hashed_key_to_api_key

Revision ID: 746efb386b17
Revises: 8d7a05fd0ad4
Create Date: 2025-04-12 12:08:56.896682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '746efb386b17'
down_revision = '8d7a05fd0ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apikey', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apikey', type_='unique')
    # ### end Alembic commands ###
