"""add threads table

Revision ID: 79e47bc3aac6
Revises: f23675767ed2
Create Date: 2025-05-12 15:49:39.142806

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "79e47bc3aac6"
down_revision = "f23675767ed2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openai_thread",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("inserted_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_openai_thread_thread_id"), "openai_thread", ["thread_id"], unique=True
    )
    op.drop_constraint(
        "credential_organization_id_fkey", "credential", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "credential", "organization", ["organization_id"], ["id"]
    )
    op.drop_constraint("project_organization_id_fkey", "project", type_="foreignkey")
    op.create_foreign_key(None, "project", "organization", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project", type_="foreignkey")
    op.create_foreign_key(
        "project_organization_id_fkey",
        "project",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "credential", type_="foreignkey")
    op.create_foreign_key(
        "credential_organization_id_fkey",
        "credential",
        "organization",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_openai_thread_thread_id"), table_name="openai_thread")
    op.drop_table("openai_thread")
    # ### end Alembic commands ###
